### ISSUE TITLE
Page view events being double counted

### ISSUE THREAD

**Issue by craigcooperxyz** [analyzify/shopify-pixels#3]
https://github.com/analyzify/shopify-pixels/blob/cf7edf17576cb45e03a3725d78a5219e1f7559d2/ga4/index.js#L82

GA4 appears to automatically track page views so this event does not need to be fired.

**Comment by craigcooperxyz** [comment]
Further to this: https://support.google.com/analytics/answer/11403294?hl=en#zippy=%2Cgoogle-tag-websites

The page view fired on the config should be disabled if we want to keep the page_view event in the main body of the script.
`gtag('config', 'TAG_ID', {
  send_page_view: false
});`

**Comment by khanakia** [comment]
Thanks will check
