### ISSUE TITLE
Missing required params on Order Items?

### ISSUE THREAD

**Issue by lmartins** [analyzify/shopify-pixels#7]
I believe Google requires you to send quantity and price for order items when tracking a purchase, the snippet is currently passing the `item_id` and `item_name`: https://github.com/analyzify/shopify-pixels/blob/a02141d678b30fb97a03ab981c832015c781b283/ga4/index.js#L20

**Comment by khanakia** [comment]
@berkb will you be able to check this ?

**Comment by berkb** [comment]
We already send the minimum required parameters, it is not mandatory to send the quantity and price. You can check the link: https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#purchase

**Comment by lmartins** [comment]
Fair enough. Feels like quite relevant info to include for the ecommerce reports, but can easily be added. Thank you for looking into it.
